version: "3"

services:
  self-adaptative-real-estate-api:
    image: stivenramireza/self-adaptative-real-estate-api:latest
    ports:
      - 5000
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.self-adaptative-real-estate-api-https.stripprefix.prefixes=/
        - traefik.http.routers.self-adaptative-real-estate-api-http.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/`)
        - traefik.http.routers.self-adaptative-real-estate-api-http.entrypoints=http
        - traefik.http.routers.self-adaptative-real-estate-api-http.middlewares=https-redirect
        - traefik.http.routers.self-adaptative-real-estate-api-https.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/`)
        - traefik.http.routers.self-adaptative-real-estate-api-https.middlewares=self-adaptative-real-estate-api-https
        - traefik.http.routers.self-adaptative-real-estate-api-https.entrypoints=https
        - traefik.http.routers.self-adaptative-real-estate-api-https.tls=true
        - traefik.http.routers.self-adaptative-real-estate-api-https.tls.certresolver=le
        - traefik.http.services.self-adaptative-real-estate-api.loadbalancer.server.port=5000

networks:
  traefik-public:
    external: true
